# $TRAVIS_PYTHON_VERSION only available if language = python
language: python

# container based has faster start up
sudo: false

dist: trusty

env:
  global:
    - OMP_NUM_THREADS=2
    - secure: "Mw2+Cln1DKdJTb3w8oPmdTfDPqIox1j4Obq537wnerxU1g6BnPuNxMFuW7mEWYuSscttM95z6LDauNjBt1z/icZrC0tjkMO4SiJZkgvzpzEWzU+TXGzobxB5kyWNHFTsmFc8GAMIQI2PNIdXaD+9zlNgLfOcbkoew22lVySWlZBScaAu0evIhHIv9TVdHb1TbN9U8hAWFzrTCYhPKXo3HN8P3bG78s+m+y2kRBB3NQA38ALlp4cuFWhGkL8iZSmNCl+SvoBTMStwkDaJynDpStMnTcypFmcUoJbQ+PzQZ5wJQ8VkwBD2sosRGTLf9W/XWVv1445IeDbmlDTv0ClYo5oUvJ1gTARqjW8fulZtmjtjLFFIBTP243pQ6fYv+QsCJhXTGwFROu8kVa3vGKB2+RcGXOTvHAN3mf9iKQkHzJMkiyjIWREoAd+Ghb75lncPwdIlDvxrcaJhUN8U6ND6gIBnRQspRKrt9xAslW1CppIsRfdDwhVKE5c4+BAPi/5pRh3IT5g8yuqBCJCB4kxuSnHfAOiGMpLp/H2mwqJtwyxe2qHff+cJNbWLNGRkJtCrcD2FTQIe7+S8dQjnY1SCfLbT8vW97/gskcRXuAEWk4ZElIANcDQj1KBXJHgUpoAYvTtrtrLO2ll2NKEcHZ++IBEWzMZdPyBYSFKCtB3KA4Y="

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

addons:
  apt:
    packages:
      - libfftw3-dev

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION astropy cython nomkl numpy pytest scipy sphinx
  - source activate test-environment

  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} ..
  - make
  - make install

script:
  # if any line in this section fails, build fails
  - set -e

  # first unit tests
  - ctest -V --output-on-failure

  # build and deploy docs only for one python version
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install doctr && pip install sphinx_py3doc_enhanced_theme && pip install sphinxcontrib-fulltoc && make docs && cd .. && doctr deploy . --built-docs build/docs/html/; fi

notifications:
  - email: false
