# $TRAVIS_PYTHON_VERSION only available if language = python
language: python

# container based has faster start up
sudo: false

dist: trusty

env:
  global:
    - OMP_NUM_THREADS=2
    - secure: "ZoYNDjr2JtjwGjQn72Gcvc8kbrxub7LSYG3gjx4qMO/AWN+gik/NlsJUAxHR1vpBzxkVYNDGFAAWVZm64gN/L3oE/xv9TkhWdKrWbDPhWctzCntVfo7DobNfY45s2czLvwdrg67PT+8p8hSQ6YLHFGqi2iOgLMFCnyRwzKsgX72SW7zglyJR5n4iBzeXJJc84ch8Kwavsf4ai5qpZKGos3CX9clkFAESGxiPPNtbtcT4vvRQ9pNF0GkBKM6zfwVKQCo3Ae/f9kPc3lzta3OC4nm53jsTp4hCKXipLjLSyri27mnfiegHAkdK1+KUHYBFQJrzno3YX+PndLIZI91bPurueYIoTxc0qhICBiCmNq8q8UeLZd5kCwjoYqMLBMif52ovEw3LBgQVkQupZoazQdUe2EeS133bRJ2VisrzMyM7k5k09kveSPJpJEkknMD+WINEojw3PeV+qpKCdqkW2xL4UKXOen1U82f6XkC7du7CG6OtY1uUgNJV+UOk9iNKekMKg29+lBDMWvDpc4buBHth/I7QZVUytH1ZDWBLMDsl0WLnEPaGL1GncYGINbp81FRw2ej/Cg3ui0s9U0DkJqZmGi8PFamLlVvyhb1rzNaemObz+CvDAhgXCA1/ynhApTHlCN7Zrg8FxLG74i5F6tAw4l3uIn7w0zfts4AFNSI="

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

addons:
  apt:
    packages:
      - libfftw3-dev

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION astropy cython nomkl numpy pytest scipy sphinx
  - source activate test-environment

  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} ..
  - make
  - make install

script:
  # if any line in this section fails, build fails
  - set -e

  # first unit tests
  - ctest -V --output-on-failure

  # build and deploy docs only for one python version
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install doctr && pip install sphinx_py3doc_enhanced_theme && pip install sphinxcontrib-fulltoc && make docs && cd .. && doctr deploy . --built-docs build/docs/html/; fi

notifications:
  - email: false
